### ISSUE TITLE
"This embed is misconfigured"

### ISSUE THREAD

**Issue by arawndinog** [thavixt/twitch-lite#1]
Seems to have malfunctioned since not long ago with the error:

Whoops! This embed is misconfigured.
(Developers: Please check your browser console for more information)

**Comment by thavixt** [comment]
Hi, thanks for letting me know!

Twitch recently changed the Embedded Player
details here: https://discuss.dev.twitch.tv/t/twitch-embedded-player-migration-timeline-update/25588

I'll take a look and fix it as soon as possible

**Comment by thavixt** [comment]
Hi @arawndinog 

I've fixed the embeds, so you can continue using the site

Unfortunately some APIs were also disabled recently, so I'll have to do some more work for the stream info (live status, viewer count) to show up.
